name: Test Failure Report
description: Report a test failure in CI/CD
title: "[Test Failure]: "
labels: ["bug", "test-failure", "ci-cd"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting the issue! Please fill in the information below.

  - type: input
    id: test-name
    attributes:
      label: Test Name
      description: Which test failed?
      placeholder: ex. Shopping.feature - Complete Shopping Journey
    validations:
      required: true

  - type: input
    id: run-link
    attributes:
      label: GitHub Actions Run Link
      description: Link to the run where the test failed
      placeholder: https://github.com/maximsoh1/PlaywrightProject/actions/runs/12345
    validations:
      required: true

  - type: dropdown
    id: workflow
    attributes:
      label: Which workflow?
      options:
        - Playwright Tests
        - PR Tests
        - Manual Test Run
        - Nightly Tests
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chromium
        - Firefox
        - WebKit
        - All browsers
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: Copy the error message from the logs
      placeholder: |
        Error: Timeout 30000ms exceeded.
        =========================== logs ===========================
        waiting for locator('#login-button')
        ============================================================
      render: shell
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce locally
      description: Can you reproduce the error locally?
      placeholder: |
        1. Run `dotnet test --filter "FullyQualifiedName~Shopping"`
        2. Test fails/passes locally
    validations:
      required: false

  - type: checkboxes
    id: frequency
    attributes:
      label: How often does it happen?
      options:
        - label: Always fails
        - label: Sometimes (flaky test)
        - label: Only in CI, works locally
        - label: First time seeing this

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
      description: Screenshots, videos, logs, etc.
      placeholder: |
        - Screenshot from artifacts shows...
        - Test started failing after commit...
        - Logs show that...
